version: '3.7'
services:
  inscription-indexer:
    build: .
    ports:
      - "3000:3000"
    environment:
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_CORE_HOST=${BITCOIN_CORE_HOST}
      - BITCOIN_CORE_PORT=${BITCOIN_CORE_PORT}
      - BITCOIN_CORE_ZMQ_PORT=${BITCOIN_CORE_ZMQ_PORT}
    volumes:
      - ./data:/app/data
    networks:
      - umbrel_network

networks:
  umbrel_network:
    external: true
